website = 'https://www.playstation.com/en-us/games/playstation-vr-worlds/?country-selector=true'
logo_sony = '//*[@id="sony-bar"]/a/span[1]'
sony_bar = '//*[@id="sony-bar"]/a/span[1]/../..'
game_overview = '//div[@class="contentgrid"]/div[@class="content-grid layout__2--a  "]/div[@class="box "]/div[@class="titleblock"]'
the_london_heist = '//p/../child::h4[text()="The London Heist"]'
key_features = '//div/h2[text()="Key features"]'
key_features_image = '//img[@alt="playstation vr worlds screenshot"]'
price = '//span/span/span[text()="$14.99"]'
add_to_Cart_button = '//div[@class="psw-l-line-left psw-hidden"]/button[@class="psw-fill-x dtm-track psw-button psw-b-0 psw-t-button psw-l-line-center psw-button-sizing psw-button-sizing--medium psw-purchase-button psw-solid-button"]'
head_nav = '//nav[@class="shared-nav shared-nav--menu-closed"]'
footer_nav_about = '//footer/nav/div/button[@role="heading"][@id="accordion-header-1"]'
footer_home_button = '//footer/div/div/nav/ul/li/a[text()][@rel="nofollow"]'
social_links = '//*[@id="accordion-panel-connect"]/ul/li[@class="social-links"]'
m_logo = '//img[@loading="lazy"][@class="psw-fade-in psw-center psw-l-fit-fill"]'
header_nav_block = '//node()[@id="shared-nav"]'
body = '//node()[@id="shared-nav"]/../../../.'
evetything_you_need_to_know = '//node()[@id="shared-nav"]/../../.././div/div/div/div/div/div/div/div[@class="page-banner__content"]'
learn_more_span = '//span[text()="Learn more"]'
div_for_learn_more_span = '//span[text()="Learn more"]/..'
discover_playstation_vr = '//*[@id="gdk__content"]/div/div[5]/div/div[2]/div/div/div[2]/div[1]'
support_button = '//*[@id="menu-button-primary--msg-support"]'
buy_on_blu_ray_disc = '//section[@class="gpdc-section theme--lightAlt  "]/div'
image_for_blu_ray_disc = '//section[@class="gpdc-section theme--lightAlt  "]/div/div/div/div/div/a'
values = '//*[@id="accordion-header-3"]'
resources = '//*[@id="accordion-header-5"]'
page_banner = '//*[@id="gdk__content"]/div/div[@class="pagebanner"]'
video = '//div[@class="media-block__inner"]/div[@class="media-block__overlay"]'
buy_gift_card = '//span[text()="Buy gift card"]'
support_logo_button = '//a[@id="link-secondary--msg-support-msg-support"]'
ESRB_rating_logo = '//img[@alt="ESRB Rating Pending Logo"]'

logo_sony_css = '#sony-bar > a > span.sony-logo.sony-bar__logo'
sony_bar_css = '#sony-bar'
price_css = 'span.psw-t-title-m'
values_css = '#accordion-header-3'
buy_gift_card_css = '#link-link-list--msg-shop-3 > span'
footer_nav_about_css = 'div > #accordion-header-1'
video_css = 'div > div > div.videoblock.carousel-cell.is-selected > div > div > div'
social_links_css = '#accordion-panel-connect > ul > li.social-links'
the_london_heist_css = 'div:nth-child(2) > div > div:nth-child(1) > div.textblock.parbase > div > h4'
support_button = '#menu-button-primary--msg-support'
